version: '3.8'

services:
  postgres:

    image: postgres:18-alpine      # только если очень нужно 18+
    
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql   # ← Вот главное изменение!

volumes:
  postgres-data: